name: CI/CD Docker-compose

on:
  push:
    branches: [master]
  
jobs:

 build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/${{ github.actor }}/BlogBackend:${{ github.sha }}

  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted, label-go]
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
#       - name: Pull Docker images
#         run: docker-compose -f /home/ubuntu/actions-runner/_work/quiz/quiz/docker-compose.yml pull
      - name: Stop and remove existing containers
        run: docker-compose -f /home/ubuntu/actions-runner/_work/BlogBackend/BlogBackend/docker-compose.yml down
      - name: Start services
        run: docker-compose -f /home/ubuntu/actions-runner/_work/BlogBackend/BlogBackend/docker-compose.yml up -d --build
      - name: Start services
        run: docker-compose -f /home/ubuntu/actions-runner/_work/BlogBackend/BlogBackend/docker-compose.yml up -d
